### ISSUE TITLE
Try styleci.io

### ISSUE THREAD

**Issue by fgrosse** [fgrosse/PHPASN1#38]
Found this on https://github.com/padraic/mockery

**Comment by fgrosse** [comment]
Fix the issues reported by the first analysis:
https://styleci.io/commits/aedabe5259afac01f6d5b12686ec50437ba989a9

Also integrate this into the pull requests (if this has not yet happend automagically)

**Comment by Spomky** [comment]
Hi,

StyleCI is a very good service, but with the default configuration, tests on PHP `5.3` will fail.
This is due to arrays that are converted from `array()` to `[]`.
If you really want to use this service, you should consider:
* change the default configuration and disable [`short_array_syntax`](https://styleci.readme.io/docs/configuration),
* drop PHP `5.3` support ([this version is no more maintained](http://php.net/supported-versions.php)).

**Comment by fgrosse** [comment]
Yes for now I thought I had just disabled the check so it doesnt scare anybody in the pull requests but seems like I failed.

Thanks for the hint anyway - I will configure it correctly one of the following days :)
