### ISSUE TITLE
Encoder usage question

### ISSUE THREAD

**Issue by korusdipl** [fgrosse/PHPASN1#44]
I now understand how the decoder works, but how can I encode [0] CONTEXT-SPECIFIC (0X80), [2] CONTEXT-SPECIFIC (0XA2), [2] CONTEXT-SPECIFIC (0XA2) things from the results of the following gist?

https://gist.github.com/korusdipl/7b145d2c67a4a03c8873

Not having the profound knowledge on ASN.1, I am having quite difficulties in encoding those stuffs back. A live snippet would be a great help.

The first result was from the binary of the OCSP output in https://gist.github.com/korusdipl/f0c3075cd61cc8d0616c

Thanks.

**Comment by fgrosse** [comment]
I noticed already in #43 that the data you are providing in the gists does not seem to correspond with the OCSP response definition of [RFC6960][1] so I am not quite sure we talk about the same thing.

In general you can parse any object as I have already shown you then you can modify it and when you think you are done you can encode it again by calling the public `getBinary` function on it.

P.S. for the future: can you put the relevant data like the used input directly in the guthub issue instead of linking to a gist?

[1]: https://tools.ietf.org/html/rfc6960#section-4.2.1

**Comment by korusdipl** [comment]
Thanks for the comment, I will study more on this.
Furthermore, I thought if I paste everything here it would be somehow messy, 
but from now on, I will copy the related stuffs directly here.
