### ISSUE TITLE
Most efficient way to parse structures?

### ISSUE THREAD

**Issue by afk11** [fgrosse/PHPASN1#45]
This library makes it easy to create encoded structures, but when it comes to parsing them, I'm a little unsure about the best way. 

I have been imperatively checking the type of each element in the structure after doing `Object::fromBinary()`.  

I wondered if it's possible to do anything similar to this, and parse a structure according to a template? If not I might take a look at PRing something for this. 

I notice some of the structures have optional parameters (eg, tbsCertificateInfo), so I'd hope to handle that also. 

```php
$structure = new Sequence(
   new Set(
      new ObjectIdentifier(),
      new Sequence(
         new Integer(),
         new BitString()
      )
   )
);

$structure->fromBinary($byteString);
```

**Comment by fgrosse** [comment]
So far I recommend defining a class for the thing you want to parse then move the parsing logic into there (including checking types etc) (check [`X509/CertificateSubject`][1] if you haven't already).
This gives you full error handling capacities, you can handle optional arguments and have full type savety with phpdoc.

The idea of defining templates sounds interesting because it can remove the necessity for the boiler plate code. However, the approach you suggested would only work if I would change the constructors to always accept no arguments which I would rather not do. Instead we could have a nested nested array of type identifiers to define such a template.

If you have yet another idea on how to traverse parsed objects while maintaining type savety and error handling I am all ears :)

I was also thinking about writing a ASN.1 compiler which could take a ASN.1 definition and compile php code which uses PHPASN1 from that. This would be a separate repository though.

[1]: https://github.com/fgrosse/PHPASN1/blob/master/lib/X509/CertificateSubject.php

**Comment by fgrosse** [comment]
I have create an experimental [TemplateParser][1] which you can check out using the [experimental/template-parser][2] branch.

I guess this is already pretty useful so I will probably merge this into master soon after I did some more error handling and improved the exception.

[1]: https://github.com/fgrosse/PHPASN1/blob/c2d491ae07fd55377809c3c3b1674a7d25dea27d/tests/ASN1/TemplateParserTest.php#L16
[2]: https://packagist.org/packages/fgrosse/phpasn1#dev-experimental/template-parser

**Comment by afk11** [comment]
Thanks, I'll bear this advice in mind. Probably will be able to send the Certificate classes your way. 

Re informing a cass about
