### ISSUE TITLE
`Object` is a special class name

### ISSUE THREAD

**Issue by Spomky** [fgrosse/PHPASN1#65]
Hi,

I have the following error on PHP 7.2 (unstable):

> Fatal error: Cannot use FG\ASN1\Object as Object because 'Object' is a special class name in ...

It looks like the `Object` name is reserved in the next major release.
Maybe something similar as the #35.

**Comment by fgrosse** [comment]
Sometimes PHP just makes me really sad :(

I will have to create a new major version of PHPASN1 if we are forced to rename this class..

I can't quite allocate time to this in the near future but I would be happy to review a PR. Any suggestions for an alternative name?

**Comment by schodemeiss** [comment]
Perhaps AbstractObject? The class is Abstract anyway?

**Comment by fgrosse** [comment]
I decided to rename `FG\ASN1\Object` to `FG\ASN1\ASNObject` and create a new version 2.0.0 with this changes.

When you upgrade you have to adapt all corresponding `use` and `extends` statements as well as type hints and all usages of `Object::fromBinary(…)`.

The later is also why I didn't want to name the type `AbstractObject` because `AbstractObject::fromBinary(…)` would have been a bit confusing (after all this always returns a concrete implementation).

**Comment by Spomky** [comment]
It makes sense and I agree with you.
What you could do is to create the `ASNObject` class in a next minor release (`v1.6`) and mark the `Object` one as deprecated.
This way, when you will release the next major release (`v2.0`), you just have to remove the deprecated class. The changes for developers will be really straightforward.

As you will create a major release, we can take the oportunity the add further improvements (drop PHP 5.6, use typehinting for the methods, implement the ASN.1 objects in the opened issues...). What do you think ?

**Comment by fgrosse** [comment]
I was considering deprecating the `Object` class but I'm not sure this would really help anybody. People who want to use PHP 7.2 will always have to update their code to use the `ASNObject` and update all `Object` imports, `fromBinary(…)` calls and inheriting classes. If there was more development in PHPASN1 (e.g. new features being developed) it would have warranted such an approach but I think this library has been quite stable over the last years and I have no plans to add new features. Thus I would just create a new major release for the sake of PHP 7.2 compatibility and be done with it.

I agree that the new release seems like a great opportunity to finally drop PHP 5.6 since everybody who wants to upgrade would do this only to get the PHP 7.2 support. I would also take pull requests for adding the remaining three objects to the library, but I don't think this should be a blocker for releasing the new version because this can be added via a normal minor release (e.g. `v2.1.0`).

With the type hints I guess you mean the new scalar type hints that came with PHP 7? I didn't really follow up on the new features there but now could be a good time to get those into the library. However I'm not sure this would add a lot of value and I honestly don't want to spend time on PHPASN1 at the moment except to fix bugs. Do you think it would be a break in backwards compatibility to add type hints later (maybe via a PR)? If the caller passes in the wrong type this should already lead to an Exception or maybe undefined behavior. Adding a type hint in that sense could be considered a feature but I'm not sure about this approach.

**Comment by Spomky** [comment]
Everything you wrote above sound legit to me.

Would you mind to create a new branch for that new major version? I will take time to propose you some PRs.

**Comment by dol** [comment]
You can avoid the notice by alias the class.
`use FG\ASN1\Object as ASNObject`

**Comment by Idriswag** [comment]
My solution will seem very strange but after several days to search I ended up reflecting myself and it works very well. In fact, since PHP 7.2 already has a reserved class for this name, I just corrected the library itself by modifying 'Object' by another name I chose and everything worked fine.
